### ISSUE TITLE
Error al lanzar Travis

### ISSUE THREAD

**Issue by javviram** [EGC-DECIDE-IO-Visualizacion/decide-io#1]
Tras integrar el proyecto con Travis, la fase `before_script` del job falla al ejecutar el manage.py.
El error final que se muestra en el log del job es: 

> The command "python manage.py migrate" failed and exited with 1 during .

Las llamadas más recientes mostrados en el log son:

> Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 168, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "db" to address: Name or service not known

Para reproducir el error, simplemente es necesario lanzar (trigger) un job en Travis de la rama master del proyecto.

El comportamiento esperado es que Travis finalice correctamente la ejecución del job.

información del entorno usado:
 - Sistema Operativo: Ubuntu
 - Navegador: firefox Quantum
 - Versión: 63.0.3

**Comment by javviram** [comment]
Problema solucionado en el commit  fb18cad6a2baae52aa678de270a6223db9c40da6.
Ha sido necesario cambiar el nombre de la base de datos de `db` a `localhost`. Además, se ha cambiado la IP definida por defecto por localhost.

**Comment by javviram** [comment]
Travis vuelve a lanzar automáticamente las pruebas tras realizar el commit y se verifica que se han ejecutado todas correctamente.

![imagen](https://user-images.githubusercontent.com/44408244/49582154-5e550780-f954-11e8-93f8-fa392c577d4b.png)
